name: DevResumeGenerator CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run : npm ci
      shell: bash
    - name: Running Build
      run : npm run build
      shell: bash
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - name: Adding artifacts to repo
      run : git --work-tree build add --all
      shell: bash
    - name: Commiting artifacts changes
      run : git commit -m "CI/CD Deploy action run by github-actions"
      shell: bash
    - name: Pushing changes to gh-pages branch
      run : git push origin HEAD:gh-pages --force
      shell: bash
